title: Richard Raphita Ompusunggu # your name (or website title) here
logo: "/images/pp2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Very enthusiast with data science, machine learning and AI. Used to work with Quipper as Operation Analyst where I have to provide information and insight to help my team in daily operation process.
  <br><br>
  Fast to adapt with new environment, like to learning new things and sharing my knowledge with others. can work under pressure and good in collaborate with other divisions.
  <br><br>
  <a href="https://www.linkedin.com/in/richardraphita/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
