title: Richard Raphita Ompusunggu # your name (or website title) here
logo: "/images/pp2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I want to be a Data Science
  <br><br>
  I want to be a Data Science 
  <br><br>
  <a href="https://www.linkedin.com/in/richardraphita/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-architect
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
