title: Richard Raphita Ompusunggu # your name (or website title) here
logo: "/images/pp2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Very enthusiast with data science, ML and AI. Used to work as Operation Analyst to provide information and insight for my team.
  Fast to adapt with new environment, like to learning new things and sharing my knowledge. Can work under pressure and good in collaborate with others.
  <br><br>
  <a href="https://www.linkedin.com/in/richardraphita/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
